server:
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/aviatrip
    username: postgres
    password: ewqe3121

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

    properties:
      javax:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE

      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        cache:
          use_second_level_cache: true
          region:
            factory_class: org.hibernate.cache.jcache.JCacheRegionFactory